### ISSUE TITLE
Checklist for pre-review stage

### ISSUE THREAD

**Issue by androlo** [androlo/compfram#1]
Webpage:

- [ ] finish tests and fix bugs
- [ ] add error data and value relations to report (requires those things in cfs and the C app first)

C program:

- [ ] add all tests
- [ ] add in relative potencies and dimensional cohesion

Protocol:

- [ ] Finish the last "under construction" sections.
